//! Explicit, idempotent workspace mutations.

mod cli;
mod plan;
mod product_crate;
mod repository;

use toml_edit::{Array, value};

use crate::Result;
use crate::cli::ScaffoldCommand;
use crate::workspace::{Workspace, read_document};

use self::plan::Plan;

pub(crate) fn run(workspace: &Workspace, command: ScaffoldCommand, dry_run: bool) -> Result {
    match command {
        ScaffoldCommand::Crate {
            semantic_name,
            bin,
            private,
        } => product_crate::add(workspace, &semantic_name, bin, private, dry_run),
        ScaffoldCommand::Cli { entrypoint } => cli::add(workspace, entrypoint, dry_run),
        ScaffoldCommand::Ci { preset } => repository::add_ci(workspace, preset, dry_run),
        ScaffoldCommand::Docs => repository::add_docs(workspace, dry_run),
        ScaffoldCommand::Agents { claude } => repository::add_agents(workspace, claude, dry_run),
    }
}

pub(crate) fn release_files(workspace: &Workspace) -> Result {
    let mut plan = Plan::new(workspace);
    let primary_manifest_path = workspace.primary_manifest_path()?;
    let mut primary_manifest = read_document(&workspace.path(&primary_manifest_path))?;
    let mut hook = Array::new();
    let version_placeholder = "{".repeat(2) + "version" + &"}".repeat(2);
    for argument in [
        "cargo",
        "xtask",
        "release",
        "changelog",
        "--tag",
        &version_placeholder,
    ] {
        hook.push(argument);
    }
    primary_manifest["package"]["metadata"]["release"]["pre-release-hook"] = value(hook);
    plan.replace(primary_manifest_path, primary_manifest.to_string());
    plan.managed(
        "release.toml",
        repository::release_toml(),
        "# generated by cargo xtask",
    )?;
    if !workspace.path("CHANGELOG.md").is_file() {
        plan.create("CHANGELOG.md", repository::changelog())?;
    }
    plan.apply(false)
}
