//! Shared planning and ownership checks for scaffold writes.

use std::fs;
use std::path::PathBuf;

use crate::Result;
use crate::workspace::{Workspace, read};

pub(crate) const GENERATED: &str =
    "<!-- generated by cargo xtask; rerun the scaffold to update -->";

pub(crate) struct Plan<'a> {
    workspace: &'a Workspace,
    writes: Vec<Write>,
}

struct Write {
    path: PathBuf,
    content: String,
    changed: bool,
}

impl<'a> Plan<'a> {
    pub(crate) const fn new(workspace: &'a Workspace) -> Self {
        Self {
            workspace,
            writes: Vec::new(),
        }
    }

    pub(crate) fn create(
        &mut self,
        path: impl Into<PathBuf>,
        content: impl Into<String>,
    ) -> Result {
        let path = path.into();
        let content = content.into();
        let absolute = self.workspace.path(&path);
        if absolute.exists() && !absolute.is_file() {
            return Err(format!("{} exists and is not a file", path.display()));
        }
        if absolute.is_file() {
            let existing = read(&absolute)?;
            if existing != content {
                return Err(format!(
                    "{} already exists and is not the generated scaffold",
                    path.display()
                ));
            }
        }
        self.push(path, content);
        Ok(())
    }

    pub(crate) fn managed(
        &mut self,
        path: impl Into<PathBuf>,
        content: impl Into<String>,
        marker: &str,
    ) -> Result {
        let path = path.into();
        if self.workspace.path(&path).is_file()
            && !read(&self.workspace.path(&path))?.starts_with(marker)
        {
            return Err(format!(
                "{} exists without the generated marker; refusing to overwrite it",
                path.display()
            ));
        }
        self.push(path, content.into());
        Ok(())
    }

    pub(crate) fn replace(&mut self, path: impl Into<PathBuf>, content: impl Into<String>) {
        self.push(path.into(), content.into());
    }

    fn push(&mut self, path: PathBuf, content: String) {
        let changed = read(&self.workspace.path(&path)).map_or(true, |current| current != content);
        self.writes.push(Write {
            path,
            content,
            changed,
        });
    }

    pub(crate) fn apply(self, dry_run: bool) -> Result {
        // Validate the entire plan, including parent paths, before any writes.
        for write in &self.writes {
            let path = self.workspace.path(&write.path);
            for ancestor in path.ancestors() {
                match fs::symlink_metadata(ancestor) {
                    Ok(metadata) => {
                        let valid = if ancestor == path {
                            metadata.is_file()
                        } else {
                            metadata.is_dir()
                        };
                        if !valid {
                            return Err(format!(
                                "{} is not a regular {}",
                                ancestor.display(),
                                if ancestor == path {
                                    "file"
                                } else {
                                    "directory"
                                },
                            ));
                        }
                    }
                    Err(error) if error.kind() == std::io::ErrorKind::NotFound => {}
                    Err(error) => {
                        return Err(format!("failed to inspect {}: {error}", ancestor.display()));
                    }
                }
                if ancestor == self.workspace.root() {
                    break;
                }
            }
        }
        for write in &self.writes {
            println!(
                "{:<9} {}",
                if write.changed { "write" } else { "unchanged" },
                write.path.display()
            );
        }
        if dry_run {
            return Ok(());
        }
        for write in self.writes.into_iter().filter(|write| write.changed) {
            let path = self.workspace.path(&write.path);
            if let Some(parent) = path.parent() {
                fs::create_dir_all(parent)
                    .map_err(|error| format!("failed to create {}: {error}", parent.display()))?;
            }
            fs::write(&path, write.content)
                .map_err(|error| format!("failed to write {}: {error}", path.display()))?;
        }
        Ok(())
    }
}
