//! Rendering for optional repository capabilities.

use std::fmt::Write as _;

use crate::Result;
use crate::cli::CiPreset;
use crate::tooling;
use crate::workspace::Workspace;

use super::plan::{GENERATED, Plan};

const CI_LEAN: &str = include_str!("../../assets/scaffold/ci/lean.yml");
const CI_FULL: &str = include_str!("../../assets/scaffold/ci/full.yml");
const AUDIT: &str = include_str!("../../assets/scaffold/ci/audit.yml");
const DEPENDABOT: &str = include_str!("../../assets/scaffold/ci/dependabot.yml");

pub(crate) fn add_ci(workspace: &Workspace, preset: CiPreset, dry_run: bool) -> Result {
    let mut plan = Plan::new(workspace);
    let full = matches!(preset, CiPreset::Full);
    plan.managed(
        ".github/workflows/ci.yml",
        tooling::workflow(if full { CI_FULL } else { CI_LEAN }),
        "# generated by cargo xtask",
    )?;
    if full {
        plan.managed("deny.toml", deny(), "# generated by cargo xtask")?;
        plan.managed("typos.toml", typos(), "# generated by cargo xtask")?;
        plan.managed(
            ".github/workflows/audit.yml",
            tooling::workflow(AUDIT),
            "# generated by cargo xtask",
        )?;
        plan.managed(
            ".github/dependabot.yml",
            DEPENDABOT,
            "# generated by cargo xtask",
        )?;
    }
    plan.apply(dry_run)
}

pub(crate) fn add_docs(workspace: &Workspace, dry_run: bool) -> Result {
    let mut plan = Plan::new(workspace);
    plan.managed(
        "CONTRIBUTING.md",
        format!(
            "{GENERATED}\n\n# Contributing\n\n\
             ```sh\ncargo xtask check\ncargo xtask test\ncargo xtask build\n```\n\n\
             Add product crates with `cargo xtask scaffold crate <semantic-name>`.\n\n\
             Keep product crate names semantic and project-prefixed; see `README.md` for the extraction rules.\n"
        ),
        GENERATED,
    )?;
    plan.managed("crates/README.md", crate_index(workspace)?, GENERATED)?;
    plan.apply(dry_run)
}

pub(crate) fn add_agents(workspace: &Workspace, claude: bool, dry_run: bool) -> Result {
    let mut plan = Plan::new(workspace);
    plan.managed(
        "AGENTS.md",
        format!(
            "{GENERATED}\n\n# Project instructions\n\n\
             - Keep changes focused on the requested behavior.\n\
             - Run `cargo xtask check` after meaningful edits.\n\
             - Run `cargo xtask test` before committing.\n\
             - Add optional project capabilities through `cargo xtask scaffold`.\n\
             - Name new product crates after a semantic ownership noun.\n"
        ),
        GENERATED,
    )?;
    if claude {
        plan.managed("CLAUDE.md", "@AGENTS.md\n", "@AGENTS.md")?;
    }
    plan.apply(dry_run)
}

pub(crate) fn release_toml() -> &'static str {
    "# generated by cargo xtask; rerun `cargo xtask release init` to update\n\
     consolidate-commits = true\n\
     sign-commit = false\n\
     sign-tag = false\n"
}

pub(crate) fn changelog() -> String {
    format!(
        "{GENERATED}\n\n# Changelog\n\n\
         All notable changes will be documented in this file.\n\n\
         <!-- next-header -->\n\n## [Unreleased]\n"
    )
}

fn crate_index(workspace: &Workspace) -> Result<String> {
    let mut crates = workspace
        .product_packages()
        .map(|package| {
            let manifest_path = package.manifest_path.as_std_path();
            let directory = manifest_path
                .parent()
                .ok_or("workspace package manifest has no parent directory")?;
            let relative = directory
                .strip_prefix(workspace.path("crates"))
                .map_err(|error| format!("failed to make crate path relative: {error}"))?;
            let targets = package
                .targets
                .iter()
                .flat_map(|target| target.kind.iter())
                .map(ToString::to_string)
                .collect::<Vec<_>>()
                .join(", ");
            let publishing = if package.publish.as_ref().is_some_and(Vec::is_empty) {
                "private"
            } else {
                "publishable"
            };
            Ok((
                package.name.clone(),
                relative.to_path_buf(),
                package.description.clone().unwrap_or_default(),
                targets,
                publishing,
            ))
        })
        .collect::<Result<Vec<_>>>()?;
    crates.sort_by(|left, right| left.0.cmp(&right.0));

    let mut output = format!("{GENERATED}\n\n# Crates\n");
    for (name, relative, description, targets, publishing) in crates {
        write!(
            output,
            "\n## [{name}](./{})\n\n{}\n\n- Targets: {targets}\n- Publishing: {publishing}\n",
            relative.to_string_lossy(),
            if description.is_empty() {
                "No package description has been written yet."
            } else {
                &description
            },
        )
        .map_err(|_| "failed to format crate index")?;
    }
    Ok(output)
}

fn deny() -> &'static str {
    "# generated by cargo xtask; rerun `cargo xtask scaffold ci --preset full` to update\n\
     [graph]\nall-features = true\n\n\
     [advisories]\nversion = 2\nyanked = \"warn\"\n\n\
     [bans]\nmultiple-versions = \"warn\"\nwildcards = \"deny\"\n\n\
     [licenses]\nversion = 2\nallow = [\"MIT\", \"Apache-2.0\", \"Apache-2.0 WITH LLVM-exception\", \"BSD-2-Clause\", \"BSD-3-Clause\", \"ISC\", \"Unicode-3.0\", \"Zlib\", \"CC0-1.0\"]\nunused-allowed-license = \"allow\"\n\n\
     [sources]\nunknown-registry = \"deny\"\nunknown-git = \"deny\"\n"
}

fn typos() -> &'static str {
    "# generated by cargo xtask; rerun `cargo xtask scaffold ci --preset full` to update\n\
     [default.extend-words]\nclippy = \"clippy\"\n\n\
     [files]\nextend-exclude = [\"CHANGELOG.md\", \"Cargo.lock\", \"*.snap\"]\n"
}
