name: "check-lint"

on:
  workflow_call:

permissions:
  contents: read

jobs:
  clippy:
    name: "cargo clippy"
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
      - name: "Install Rust toolchain"
        uses: moonrepo/setup-rust@v1.3.0
        with:
          inherit-toolchain: true
      - uses: Swatinem/rust-cache@v2
      - name: "Clippy"
        run: cargo xtask check
