name: "check-fmt"

on:
  workflow_call:

permissions:
  contents: read

jobs:
  rust:
    name: "cargo fmt"
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
      - name: "Update Rustup"
        run: rustup self update
      - name: "Install Rust toolchain"
        uses: moonrepo/setup-rust@v1.3.0
        with:
          inherit-toolchain: true
      - name: "Format"
        run: cargo fmt --all --check
