name: "test"

on:
  workflow_call:

permissions: {}

jobs:
  test:
    name: "cargo test"
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: Swatinem/rust-cache@v2
      - name: "Test"
        run: cargo test --workspace --locked
